site_name: MeanderingMind
site_description: It's a Mia!
site_url: https://meanderingmind.me/
edit_url: https://github.com/Adminisnyator/homepage.git
# Please push via ssh to git@github.com:Adminisnyator/homepage.git

nav:
  - Home: index.md
  - Curriculum Vitae: cv.md

plugins:
  - search:
      indexing: 'full'
  - gen-files:
      scripts:
        - src/gen_pages.py

docs_dir: docs
draft_docs: vault
site_dir: ../site
exclude_docs: |
  !.well-known

theme:
  name: landing

  favicon: "assets/images/favicon.svg"
  avatar: "assets/images/mia.jpg"

  tagline: |
    /[Meandering of a lost mind](http://ipa-reader.xyz/?text=lændɪŋ)/

  page_source:
    link: https://meanderingmind.me

  socials:
    - label: Email
      link: mailto:mia.hallas@meanderingmind.me
      icon: at
    - label: GitHub
      link: https://github.com/Adminisnyator
      icon: [brands, github]
    - label: Curriculum Vitae
      link: https://meanderingmind.me/cv/
      icon: home

  toc_level: 0
  header_layout:
  - avatar
  - title
  -
  - tagline
  -
  - socials
  footer: "Made with mkdocs <3"

  # background
  avatar_size: 10rem
  # background_gradient_colors:
  # - color-mix(in srgb, var(--text) 60%, transparent)
  # - transparent
  # - color-mix(in srgb, var(--text) 60%, transparent)

  background_image: "assets/images/bg.png"
  content_box_opacity: 98%
  content_box_padding: 14rem

  # colours
  primary_color: "#822000"
  secondary_color: "#c9ad6a"
  tertiary_color: "#822000"
  # shades
  base_color: "#fcf5e5"
  mantle_color: "#e0e5c1"
  crust_color: "#c9ad6a"
  overlay_color: "#822000"
  # text
  text_color: "#000000"

  # background-specific text
  primary_text_color: var(--hltext)
  secondary_text_color: var(--text)
  tertiary_text_color: var(--text)
  base_text_color: var(--text)
  mantle_text_color: var(--text)
  crust_text_color: var(--text)
  overlay_text_color: var(--hltext)

  # fonts
  heading_font: Crimson Text
  body_font: Alegreya
  mono_font: Source Code Pro


copyright: Copyright &copy; 2025 <a href="https://meanderingmind.me">Mia Evelyn Hallas</a>.
